### ISSUE TITLE
启动bat文件最后显示缺少某个函数是为什么

### ISSUE THREAD

**Issue by XavierZYZ** [MoJIeAIGC/IDMVTON_CN#1]

**Comment by MoJIeAIGC** [comment]
可以贴图看下，或者手动pip安装缺失依赖。pip install XXX

**Comment by AnzioNiko** [comment]
<img width="826" height="371" alt="Image" src="https://github.com/user-attachments/assets/cecc6ea1-c442-4043-afe6-f899426dec42" />这个问题现在还有，视频评论区有人说加一个依赖，要多下一大堆gradio的各种版本，现在也没下好不知道是否可行
